MinAlertLevel = suggestion
Packages = Microsoft

[*.md]
BasedOnStyles = Microsoft

# Disable rules that are controversial or unnecessarily-opinionated
Microsoft.Avoid = NO
Microsoft.Contractions = NO
Microsoft.GeneralURL = NO
Microsoft.Headings = NO
Microsoft.HeadingAcronyms = NO
